/**
 * MADR export (the MADR bridge, export half — roadmap's "compiler" projection).
 *
 * Renders the PUBLIC decision graph as a regenerated MADR 3.x corpus: one
 * NNNN-slug.md per decision, superseded links derived from superseded_by /
 * valid_to, rejected alternatives under Considered Options. The projection is a
 * DISPOSABLE build artifact — the graph stays the source of truth, numbers are
 * assigned per export (date order), and every emitted file carries a generated
 * marker. The writer only ever overwrites files bearing that marker: a
 * hand-written ADR corpus in the target directory is untouchable (refused with
 * a warning), so `hunch import-adr` + `hunch export-adr` can share a repo
 * without the export eating its own import source.
 *
 * Privacy boundary: rendering takes an explicit PUBLIC-only decision list —
 * callers must pass store.json.loadAll("decisions"), never the overlay union.
 */
import type { Decision } from "../core/types.js";

export const MADR_EXPORT_MARKER = "<!-- hunch:generated madr-export — regenerated by `hunch export-adr`; edits will be overwritten -->";

export interface MadrFile {
  /** file name only, NNNN-slug.md */
  name: string;
  text: string;
  decisionId: string;
}

export interface MadrExportResult {
  files: MadrFile[];
  /** the one-line Backstage catalog-info annotation for this corpus */
  backstageAnnotation: string;
}

function slugify(title: string): string {
  const s = title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 60)
    .replace(/-+$/, "");
  return s || "decision";
}

function statusLine(d: Decision, nameOf: Map<string, string>): string {
  if (d.status === "superseded") {
    const successor = d.superseded_by ? nameOf.get(d.superseded_by) : null;
    return successor ? `superseded by [${successor}](${successor})` : "superseded";
  }
  return d.status;
}

/** Render one decision as a MADR 3.x document. Deterministic: content depends
 *  only on the decision record and the corpus's name map. */
export function renderMadr(d: Decision, nameOf: Map<string, string>): string {
  const lines: string[] = [];
  lines.push("---");
  lines.push(`status: ${statusLine(d, nameOf)}`);
  const date = (d.valid_from ?? d.date).slice(0, 10);
  lines.push(`date: ${date}`);
  lines.push("---");
  lines.push("");
  lines.push(MADR_EXPORT_MARKER);
  lines.push("");
  lines.push(`# ${d.title}`);
  if (d.context) {
    lines.push("");
    lines.push("## Context and Problem Statement");
    lines.push("");
    lines.push(d.context);
  }
  if (d.alternatives_rejected.length) {
    lines.push("");
    lines.push("## Considered Options");
    lines.push("");
    lines.push(`- ${d.title}`);
    for (const alt of d.alternatives_rejected) lines.push(`- ${alt}`);
  }
  lines.push("");
  lines.push("## Decision Outcome");
  lines.push("");
  // Canonical MADR phrasing so the projection round-trips through import-adr:
  // the "Chosen option:" line is what marks the winner among Considered Options.
  if (d.alternatives_rejected.length) {
    lines.push(`Chosen option: "${d.title}", because of the following.`);
    if (d.decision) {
      lines.push("");
      lines.push(d.decision);
    }
  } else {
    lines.push(d.decision || d.title);
  }
  if (d.supersedes && nameOf.get(d.supersedes)) {
    lines.push("");
    lines.push(`Supersedes [${nameOf.get(d.supersedes)}](${nameOf.get(d.supersedes)}).`);
  }
  if (d.consequences.length) {
    lines.push("");
    lines.push("### Consequences");
    lines.push("");
    for (const c of d.consequences) lines.push(`- ${c}`);
  }
  lines.push("");
  lines.push(`<!-- source: ${d.id}${d.commit ? ` @ ${d.commit}` : ""} -->`);
  lines.push("");
  return lines.join("\n");
}

/** Project a PUBLIC decision list into a MADR corpus. Numbering is date order
 *  (valid_from, then date, then id for determinism) and assigned per export —
 *  the projection is disposable, links inside it are internally consistent. */
export function exportMadrCorpus(decisions: readonly Decision[], dirForAnnotation: string): MadrExportResult {
  const sorted = [...decisions].sort((a, b) => {
    const ka = `${a.valid_from ?? a.valid_to ?? a.date} ${a.valid_to ? 0 : 1} ${a.id}`;
    const kb = `${b.valid_from ?? b.valid_to ?? b.date} ${b.valid_to ? 0 : 1} ${b.id}`;
    return ka < kb ? -1 : ka > kb ? 1 : 0;
  });
  const nameOf = new Map<string, string>();
  const taken = new Set<string>();
  sorted.forEach((d, i) => {
    let slug = slugify(d.title);
    while (taken.has(slug)) slug = `${slug}-${d.id.slice(4, 10)}`;
    taken.add(slug);
    nameOf.set(d.id, `${String(i + 1).padStart(4, "0")}-${slug}.md`);
  });
  const files = sorted.map((d) => ({
    name: nameOf.get(d.id)!,
    text: renderMadr(d, nameOf),
    decisionId: d.id,
  }));
  return {
    files,
    backstageAnnotation: `backstage.io/adr-location: ${dirForAnnotation}`,
  };
}

/** True when an existing file may be overwritten by the export: only our own
 *  generated output ever qualifies. */
export function isRegenerableMadr(existingText: string): boolean {
  return existingText.includes(MADR_EXPORT_MARKER);
}
